### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by simahawk** [camptocamp/odoo-dj#120]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] base_dj
- [ ] dj_account
- [ ] dj_compilation_account
- [ ] dj_compilation_account_enterprise
- [ ] dj_compilation_account_payment_mode
- [ ] dj_compilation_stock
- [ ] dj_core
- [ ] dj_crm
- [ ] dj_hr
- [ ] dj_sale
- [ ] dj_survey
- [ ] dj_website
